upcoming_movies:
    path: /movies/upcoming
    controller: App\Controller\MoviesController::upcomingMovies

movie_details:
    path: /movies/{movieId}
    controller: App\Controller\MoviesController::movieDetails
    requirements:
        movieId: '\d+'

movie_by_query:
    path: /movies/query
    controller: App\Controller\MoviesController::byQuery
